---

# Find the primary group of users whose group has not been manually defined
- name: users > Find primary groups
  command: "id -g -n {{ item.user }}"
  loop: "{{
    manala_ohmyzsh_users | flatten | selectattr('state', 'undefined') | list
    +
    manala_ohmyzsh_users | flatten | selectattr('state', 'defined') | rejectattr('state', 'equalto', 'ignore') | list
  }}"
  when:
    - item.state|default('present') == 'present'
    - item.group is not defined
  register: __manala_ohmyzsh_users
  changed_when: false

# Pair users with their found groups
- name: users > Pair primary groups
  set_fact:
    # Waiting for the ansible 2 "combine" filter...
    __item: "{% set __item = item.0.update(({}) if (item.1 is skipped) else ({'group': item.1.stdout})) %}{{ item.0 }}"
  loop: "{{
    (
      manala_ohmyzsh_users | flatten | selectattr('state', 'undefined') | list
      +
      manala_ohmyzsh_users | flatten | selectattr('state', 'defined') | rejectattr('state', 'equalto', 'ignore') | list
    )|zip(__manala_ohmyzsh_users.results)|list }}"
  register: __manala_ohmyzsh_users

# Flatten results structure to the original variable
- name: users > Flatten primary groups
  set_fact:
    manala_ohmyzsh_users: "{{ __manala_ohmyzsh_users.results|map(attribute='ansible_facts.__item')|list }}"

- name: users > Templates
  template:
    src: "{{ item.template|default(manala_ohmyzsh_users_defaults.template|default('users/_default.j2', true), true) }}"
    dest: "{{ item.dir|default('~' ~ item.user, true) }}/.zshrc"
    owner: "{{ item.user }}"
    group: "{{ item.group|default(omit) }}"
    mode: "0644"
  loop: "{{ manala_ohmyzsh_users }}"

- name: users > Shells
  user:
    name: "{{ item.user }}"
    shell: /bin/zsh
  loop: "{{ manala_ohmyzsh_users }}"
